doc/git_configuration.rst

This is the instruction file on how to contribute to ROSS project using git.

Git configuration file

---

ross/__init__.py
ross/materials.py

Here is the implementation of the Material class that can be saved in a JSON format.

Implementation of  the Material class

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/element.py
ross/shaft_element.py

This file should replace the main `class Element` from the shaft_element.py, disk_element.py, bearing_seal_element.py files

Add element.py file

---

ross/rotor_assembly.py

Add a method to calculate the static displacement of a rotor due to disks' weight.

Add static analysis method

---

README.md
docs/git_configuration.rst
docs/index.rst
docs/introduction.rst
docs/tutorial.rst

Documentation was updated to look more clear and with more references.
An introduction.rst file was created. It explains the very first steps
to start using ROSS. Unlike the tutorial, which will guide through how
to run the program, introduction tells what the user needs to install
in order to get the program ready to run. Close #53

Update documentation and include introduction

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/rotor_assembly.py
ross/shaft_element.py

Add bokeh plot style to "static" method.
Add deformed and undeformed shaft plots.
Add gravity effect to all elements' nodes (vertical direction - "y").
Correct the loop index while calculating the shaft displacement.
Add bokeh plot style to "from_section" classmethod.

Add Bokeh plotting style

---

ross/rotor_assembly.py

Add new plot to static method - shearing force
Change the name of some graphs to make it more readable

Add new diagram

---

ross/fluid_flow/fluid_flow.py

The user will no longer provide the position of the rotor as
argument to instantiate fluid flow. Instead, they will provide
the eccentricity, which is the distance between the stator and
rotor centers. The rotor will always be placed at -45 degrees,
and theta will start counting from this point, as commonly seen
found in literature. Close #82

Add eccentricity parameter to fluid flow

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/element.py
ross/rotor_assembly.py
ross/shaft_element.py

There was a mistake while saving the coefficients to toml format.

Fixing the save_bearing_seal_element() method

---

ross/bearing_seal_element.py
ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py
ross/tests/test_rotor_assembly.py

This Pull Request is to replace the last PR related to this issue. Since the last one was getting too difficult to solve the conflicts. 
EDIT 1: I'm also adding the Bokeh plots in this PR instead of opening a new branch / PR to avoid future conflicts.
EDIT 2: The function interp1d from module scipy.interpolate was not
being imported. This PR also corrects this problem.

Add tests for static analysis and convergence analysis

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/materials.py
ross/shaft_element.py

__repr__ method implementation for:
- DiskElement
- BearingElement
- Material

__repr__ method implementation

---

ross/results.py

This commit implements plotting using bokeh to generate magnitude and phase plot to ForcedResponse class.

Add bokeh plot to ForcedResponse() class

---

ross/bearing_seal_element.py
ross/fluid_flow/fluid_flow.py
ross/tests/test_fluid_flow.py

A bearing can now be instantiated from fluid flow by giving fluid flow parameters to a bearing method.

Add bearing instantiation from fluid flow

---

ross/rotor_assembly.py

Add bokeh plotting as alternative to matplotlib to plot graphs.

Add bokeh plot to "plot_level1" and "plot_ucs"

---

ross/__init__.py

Add __init__.py file to fluid flow and change version to 0.0.2.

Pypi bug fix

---

ross/__init__.py

Update init file to version 0.1.0, which is already in PyPI

Update version to 0.1.0

---

ross/results.py
ross/rotor_assembly.py

Add log dec and precession to the "docstring's return"

Improving results

---

ross/materials.py

the method save_material was changing the current working directory, this PR solves this issue.

Fixing save_material changing CWD.

---

ross/fluid_flow/fluid_flow.py

Also, among other small changes, plots now distinguish the entry matrix, if numerical or analytical. If both were calculated, they plot both so that the user can compare them.
Close #140

Change plots so that they will not automatically plot

---

ross/fluid_flow/fluid_flow.py
ross/tests/test_fluid_flow.py

Fix the bearing type definition and also add a new test that checks if a second analytical way to calculate the pressure matrix matches the numerical way.
Close #175

Fix bearing type definition and add new test

---

ross/__init__.py

Updated __init__.py to new version, which is already updated in PyPI.

Update to version 0.1.1

---

ross/results.py

Unbalance response was not plotting when calling it using matplotlib

Fix bug - plotting unbalance response

---

docs/examples/example_05_05_01.ipynb
ross/fluid_flow/fluid_flow.py

Add example 9 that explores the fluid flow subpackage

---

ross/shaft_element.py

Add a function to instantiate shafts from an input table

---

ross/results.py
ross/rotor_assembly.py

- Removes the code related to plotting from this file. It was transfered to results.py
- Replaces the method name from plot_time_response to run_time_response.
- Fix ForcedResponseResults docstring

 Move time response plotting to results

---

ross/fluid_flow/fluid_flow.py

Fix the center of the stator at the origin and describe the position of the rotor in function of the
eccentricity.

Modify the internal radius and outer radius functions in fluid_flow

---

ross/bearing_seal_element.py
ross/tests/test_bearing_seal_element.py

The from_table method was too strict. I added a few routines so that the user can vary the format of the table a bit more. I also added a simple test.
Close #207

Fix xl file bug

---

ross/tests/test_fluid_flow.py

Add plot tests

---

ross/utils.py

This will fix a few bugs that have been occurring when instantiating from tables.
Close #237

Drop NaNs from table

---

ross/tests/test_bearing_seal_element.py
ross/utils.py

The conversion to metric when bearings were instantiated from table was
left out by mistake. I'm adding it now.

Add metric conversion to bearing elements from table

---

ross/fluid_flow/fluid_flow.py
ross/tests/test_fluid_flow.py

Add fluid flow long bearing

---

ross/fluid_flow/fluid_flow.py

Add examples to fluid flow documentation

---

ross/utils.py

Add example to utils documentation

---

ross/api_report.py
ross/results.py

Well, since I have forgotten to add the .py extention on api_report file, the CI's were not running the tests on it. And now that I did it, the building is failing due some tests.
This PR tries to fix this problem on api_report.py and in results.py (with new docstrings on ModeShapeResults)
The last PR (#272) was a failure actually.

Fixing doctests

---

ross/fluid_flow/fluid_flow.py

Add attitude angle calculation

---

ross/fluid_flow/fluid_flow.py
ross/tests/test_fluid_flow.py

This function calculates the forces of the oil film in the N and T directions, ie, in the opposite direction to the eccentricity and in the tangential direction.
Related to issue #261

Add calculate_oil_film_force function

---

ross/__init__.py
ross/bearing_seal_element.py
ross/disk_element.py
ross/element.py
ross/results.py
ross/shaft_element.py
ross/tests/test_bearing_seal_element.py
ross/tests/test_disk_element.py
ross/tests/test_shaft_element.py
ross/utils.py

This PR adds a matrix visualization function. This function gives some visualization of a given matrix, displaying values on a heatmap. This can be useful in checking the global matrices’ assembling:
There are also some corrections and formatting of the code.

Add matrix visualization

---

ross/bearing_seal_element.py
ross/disk_element.py

Improve documentation in disk element

---

.gitignore
docs/_templates/autosummary/base.rst
docs/_templates/autosummary/class.rst
docs/api.rst
docs/conf.py

This adds the autosummary directive to the api.rst file.
The API page is automatically generated with the following results:

Improve docs web

---

ross/shaft_element.py

Improve documentation in shaft_element.py

---

ross/api_report.py

- Add docstring to `.from_saved_rotor()`
- Add attributes to classmethod `from_saved_rotor` to match the class `Report`
- Modify `.unbalance_response example()`

Improve documentation in api_report.py

---

ross/available_materials.toml

Add A216WCB to available materials.

Add A216WCB to available materials

---

ross/rotor_assembly.py

Sort shaft elements based on node

---

ross/element.py

Improve documentation in element.py

---

ross/results.py

This commit splits the plot method in four:
- plot_deformation()
- plot free_body_diagram()
- plot_shearing_force()
- plot_bending_moment()
This is related to Issue #303.

Split StaticResults plot method

---

ross/results.py

This class is not used anymore. See #172 for more info.

Remove Results class

---

docs/examples/example_05_05_01.ipynb

Fix fluid flow errors due to changes

---

setup.py

Add requirement for pandas >= 0.23

---

paper/paper.bib
paper/paper.md

Add paper and reference

---

ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py

Related to Issue #327 
Follows the PR #338 
- Add new attribute "tag" to name the rotor;
- Add CG and Moment of Inertia parameters;
- Add new attributes to .summary() method;
- Add a system of Tabs that allows the user to alternate between
tables;
- Tables are separeted in:
- Rotor summary
- Shaft summary
- Disk summary

Improvements to SummaryResults

---

ross/results.py
ross/rotor_assembly.py

This fixes some issues on the force plots such as figure size and
labels.

Fix forced plots

---

ross/shaft_element.py
ross/utils.py

Fix utils cyclic import

---

ross/bearing_seal_element.py

This factor will scale the bearing drawing.

Add bearing scale factor

---

ross/rotor_assembly.py

Fix bearings not connecting to tapered elements

---

ross/disk_element.py
ross/element.py
ross/results.py

Use disk default color for plotting.

Use disk default color

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/tests/test_fluid_flow.py

Based on a given load, find eccentricity iteratively to match the equilibrium position.

Find eccentricity iteratively

---

docs/_static/style.css
docs/conf.py
docs/refs.bib
ross/bearing_seal_element.py
ross/disk_element.py
ross/element.py
ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py
ross/tests/test_bearing_seal_element.py
ross/tests/test_examples.py
ross/tests/test_rotor_assembly.py
ross/utils.py
setup.py

Many changes to the documentations regarding the format.
I had to change some docstrings to add a blank line after each section so that sphinx could render the documentation properly.

Improve docs

---

paper/paper.md

Add affiliations to joss paper

---

ross/tests/test_bearing_seal_element.py
ross/utils.py

Add us units support for bearing from table instantiation

---

ross/api_report.py

For the level 2 stability analysis additional sources that contribute to the rotor stability shall be considered. These sources shall replace the cross-coupling Qa, calculated in the stability analysis level 1

Add stability analysis level 2

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/tests/test_fluid_flow.py

Improve equilibrium position method

---

ross/results.py
ross/rotor_assembly.py

3D plots for orbit response

---

docs/examples/example_05_05_01.ipynb

After modifications to the fluid_flow structure, some names have been changed. This was causing the error in example 05_05_01. This pull request closes the issue #390

Correct the fluid flow error in example_05_05_01.ipynb

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/fluid_flow/fluid_flow_geometry.py
ross/tests/test_fluid_flow.py

Improve load method 

---

ross/__init__.py

Bump version to 0.2.0

---

paper/paper.bib
paper/paper.md

I am making this PR to fix some issues raised by danielskatz in the JOSS pre-review:
> @raphaeltimbo - note that whedon found 2 DOIs that should be added to your paper. Also, please check the references to make sure the cases (upper vs lower) are correct, and add {}s in the .bib file where needed to protect cases. Once you have made changes, enter a new comment in this issue with @whedon generate pdf to regenerate the pdf to make sure it looks right.
> I also see a number of spelling mistakes in the paper - please check this as well and make needed fixes. e.g. softares, comercial, ...

Implement comments from JOSS pre-review

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_graphics.py

One of the boundary conditions for calculating the pressure matrix was being calculated with the wrong parameter. This committ corrects that.

Correct boundary conditions

---

ross/results.py
ross/rotor_assembly.py

Add mode_shape 2D graph

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/rotor_assembly.py
ross/tests/test_rotor_assembly.py

- Add CoAxialRotor class
- Add new example to run CoAxialRotor class
- Adapt `.plot_rotor()` method to plot co axial rotor system.
- Add ["shaft_number"] column to the dataframe to identify each shaft in the rotor system.
- Run Black to format code.
I still need to add some initial tests, so I'm leaving it in WIP, while you can check it and comment.

Add CoAxialRotor class

---

CONTRIBUTING.rst
deploy_docs.sh
docs/conf.py
ross/fluid_flow/fluid_flow_graphics.py
ross/tests/test_fluid_flow.py

This PR changes the process to update our documentation.
Following [semantic versioning](https://semver.org/) we will have branches that follow the current minor version (e.g. 0.3, 0.4 etc.). When we merge some modification to the docs, Travis CI will run the `deploy_docs.sh` script, which will check if the modification is being made to the branch that refers to the current released version. If that is the case, Travis will build the documentation and push the updated docs to the ross-website repo.
This avoids updating the documentation on every push to the master branch which can cause inconsistencies between the released version and the website docs.

Change how docs are updated

---

CONTRIBUTING.rst

This improves the CONTRIBUTING.rst file, giving instructions on how to set the development environment. We should also merge this to the 0.3 branch so that the docs get updated.

Improve CONTRIBUTING.rst

---

ross/bearing_seal_element.py

This class creates a magnetic bearing element. 
The element can be created by:
- defining directly the stifness and damping coefficients with the method **__init__**;
- defining the magnetic parameters g0, i0, ag, nw, alpha and the porportional and derivative gains of a PID controller  kp_pid, kd_pid with the method **param_to_coef**.
The reference for the equations is:
**Book**: Magnetic Bearings. Theory, Design, and Application to Rotating Machinery
**Authors**: Gerhard Schweitzer and Eric H. Maslen
**Page**: 84-95 (magnetic parameters) and 354 (PID gains)

Class MagneticBearingElement was created

---

ross/__init__.py
ross/api_report.py

Related to Issue #472 
Closes TODO list from PR #498 
- In `api_report.py`
- Replace bokeh.widgetbox with bokeh.Column
- Update docstrings

Removing deprecations from api_report.py

---

ross/materials.py

Make sure we have floats for material properties

---

paper/paper.md

Add example to new elements

---

paper/paper.md

Minor readability improvements

---

requirements.txt

Add bokeh required version

---

ross/fluid_flow/fluid_flow.py

Change in the method used to solve the linear system in the resolves_matrix method of the FluidFlow Class

Sparse matrix method

---

ross/disk_element.py
ross/element.py
ross/rotor_assembly.py

Argument to scale the disk patch. Used to increase (scale_factor > 1.0) or reduce (scale_factor < 1.0) the size of disk patches when plotting the rotor.

Add scale_factor argument to DiskElement class

---

ross/bearing_seal_element.py

Explain how ROSS handles SealElement differently from BearingElement

Improve SealElement documentation

---

ross/bearing_seal_element.py

This changes the __repr__ so that we have the same repr as the
coefficients. It also adds a getitem method so that bearing.kxx[0] does
not raise an exception.

Fix coefficients

---

ross/bearing_seal_element.py
ross/disk_element.py
ross/point_mass.py
ross/tests/test_stochastic_elements.py
ross/tests/test_units.py
ross/units.py

The arguments can be passed as pint.Quantity.

Add units to the DiskElement, BearingElement and PointMass classes

---

requirements.txt
ross/api_report.py
ross/bearing_seal_element.py
ross/disk_element.py
ross/element.py
ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_graphics.py
ross/point_mass.py
ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py
ross/stochastic/st_bearing_seal_element.py
ross/stochastic/st_disk_element.py
ross/stochastic/st_materials.py
ross/stochastic/st_point_mass.py
ross/stochastic/st_results.py
ross/stochastic/st_results_elements.py
ross/stochastic/st_rotor_assembly.py
ross/stochastic/st_shaft_element.py
ross/tests/test_api_report.py
ross/tests/test_fluid_flow.py
ross/tests/test_stochastic_elements.py
ross/utils.py

This PR aims to replace Matplotlib and Bokeh plotting libraries with Plotly.
Files updated so far:

Replacing plotting libraries

---

ross/results.py
ross/stochastic/st_results.py

Related to Issue #553.
When running and plotting forced response analysis, ROSS returns 3 graphs:
- Amplitude vs Frequency (cartesian plot)
- Phase Angle vs Frequency (cartesian plot)
- Amplitude vs Phase Angle (polar plot)
In this last one, the user has access to the frequency info by hovering the mouse over the points. I did not add frequencies text marks to avoid polluting the graph visualization.

Polar plot to Forced Response

---

ross/api_report.py
ross/rotor_assembly.py
ross/stochastic/st_rotor_assembly.py
ross/tests/test_rotor_assembly.py

Add "run_" to unbalance_response name 

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/fluid_flow/fluid_flow_geometry.py

Include the parameter called reynolds number. This number denotes the ratio between fluid inertia (advection) forces and viscous-shear forces.

Reynolds number

---

ross/results.py
ross/rotor_assembly.py
ross/tests/test_rotor_assembly.py

- Interpolating data could generate an odd aspect to the bending moment graph.
- Changes `disp_y` to `deformation` for better understanding the attribute.
- Make the code more readable.
- Make better usage of the stiffness and mass matrices properties.
- Forces are now calculated and displayed for each element, presenting a matrix with forces on
left and rigth stations of the shaft_element.
- Forces are separated into shaft weight forces and bearing / disk forces in this matrix.
- Removes a bug when calculating bearing forces with n_link parameter on CoAxialRotor models.

More efficient code for static analysis 

---

ross/rotor_assembly.py

Related to Issue #559 
This method checks if the array used to `run frequency response` (`run_unbalance_response`, `forced_response`) or `run_campbell` analysis causes the bearing coefficients to be extrapolated, thus, raises an warning

Warning to extrapolating coefficients 

---

ross/disk_element.py

Fix ValueError when inputting an integer to disk properties

---

ross/rotor_assembly.py

Fix index to slice modal parameters

---

ross/rotor_assembly.py

Complementing PR #597. 
- run_unbalance_response()
- forced_response()

Include option for clustering points to other methods

---

ross/available_materials.toml
ross/bearing_seal_element.py
ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/rotor_assembly.py
ross/stochastic/st_bearing_seal_element.py
ross/tests/test_fluid_flow.py

This pull request closes issue #435 . It is now possible to numerically calculate the stiffness and damping coefficients in the bearings.
Close #435

Stiffness and damping coefficients

---

ross/api_report.py
ross/rotor_assembly.py
ross/utils.py

These modifications should be in PR #582, but I did not see that at the time.

Remove parameters related to plot style from plot

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/fluid_flow/fluid_flow_graphics.py
ross/tests/test_fluid_flow.py

This pull request is related to issue #616 
@rodrigomoliveira1 , I tried to reduce as many attributes as possible. Some could be removed, but are used many times in the code and calculating them several times would increase the time it takes to run the code.
Do you think we should modify anything else?

Reduce attributes

---

ross/materials.py
ross/shaft_element.py
ross/tests/test_materials.py

Change .use_material() to .load_material()

---

ross/rotor_assembly.py

BearingElement6DoF is not being positioned to plot 6 DoF rotors.

Define positions for 6dof bearings.

---

ross/fluid_flow/fluid_flow_geometry.py

Corrected the function that calculates the eccentricity ratio in the short bearing.
This pull request closes the issue #647

Correct the eccentricity ratio in the short bearing

---

deploy_docs.sh

Add debug information to deploy docs

---

ross/bearing_seal_element.py
ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/fluid_flow/fluid_flow_geometry.py
ross/tests/test_fluid_flow.py

In this Pull Request, the equilibrium position for long bearings is calculated by means of an iterative method. It should work well for bearings with non-cylindrical geometry.

Find equilibrium position

---

ross/fluid_flow/fluid_flow.py

This pull request solves the issue #662

Solve bug in init of the FluidFlow

---

ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py

- Users will be able to pick an unit to plot the rotor model and mode shapes (2d and 3d).
- Subplots with same xaxes values are merged in `ForcedResponseResults` `.plot()` and `plot_deflected_shape()`.

Fix bugs in plots output

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/fluid_flow/fluid_flow_geometry.py
ross/tests/test_fluid_flow.py

This pull request includes the elliptical bearing as a geometry option for FluidFlow. Force upgrades were needed to adapt the new possibilities. 
Close #649

Eliptical bearing

---

ross/fluid_flow/fluid_flow_graphics.py

Observing the eccentricity may be difficult due the small scales we have. Introducing the this scaling factor will help the users to understand the eccentricity behaviour.
For example:
The `scale_factor` argument will modify the rotor radius and the eccentricity display. To avoind missunderstanding, I've modified the data to be displayed on the plot. The plot would return the coordinates for each point, but now it displays relevant data to the user:
- attitude angle
- eccentricity
- radius rotor
- radius stator
- Ellipticity ratio
- shape geometry
The `scale_factor` ranges from 0 to 1, where 1 is the True scale (1:1) and 0 is the maximum one can reduce.
The default value is 1.0.
```python
>>> my_fluid_flow = fluid_flow_example()
>>> fig = plot_eccentricity(my_fluid_flow, …
```

Add scale factor to .plot_eccentricity() in fluidflow

---

ross/bearing_seal_element.py
ross/rotor_assembly.py

These changes are discussed on Issues #678 and #679.

Minor adjustments to ROSS

---

ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_geometry.py

This pull request introduces a new wear bearing geometry. The model used was proposed by Dufrane (1983) and has been validated experimentally by Hashimoto (1986). The user needs to report the greatest wear depth and its angular position from the vertical axis.
Dufrane, K. F., Kannel, J.W., and McCloskey, T. H., "Wear of Steam Turbine Journal Bearings at Low Operating Speeds." J. Lubr. Technol., Trans. ASME. 105,3, pp 313-317 (1983).
Hiromu Hashimoto , Sanae Wada & Katsuhiro Nojima (1986) Performance Characteristics of Worn Journal Bearings in Both Laminar and Turbulent Regimes. Part I: Steady-State Characteristics, A S L E Transactions, 29:4, 565-571, DOI: 10.1080/05698198608981721

Wear bearing

---

.pre-commit-config.yaml
ross/bearing_seal_element.py
ross/defects/abs_defect.py
ross/defects/integrate_solver.py
ross/defects/misalignment.py
ross/fluid_flow/fluid_flow.py
ross/fluid_flow/fluid_flow_coefficients.py
ross/results.py
ross/rotor_assembly.py
ross/stochastic/st_disk_element.py
ross/stochastic/st_materials.py
ross/stochastic/st_point_mass.py
ross/stochastic/st_results.py
ross/stochastic/st_shaft_element.py
ross/tests/test_bearing_seal_element.py
ross/tests/test_fluid_flow.py
ross/tests/test_materials.py
ross/tests/test_stochastic_elements.py
ross/tests/test_stochastic_rotor_assembly.py

- Add test for BearingFluidFlow
- Extract .from_fluid_flow method to a class
This is more in line with how we have all the Bearing classes, and
makes it easier for the user to find it.
Closes #695.

extract fluid flow

---

.travis.yml

This adds conda to our travis build. 
Closes #708.

Change travis build to use anaconda

---

docs/api.rst

This adds some bearing classes to our api docs.

Add new bearing classes to api docs

---

ross/defects/abs_defect.py
ross/results.py
ross/rotor_assembly.py
ross/tests/test_results.py

* Add `link_nodes` attribute to Rotor object that holds the nodes created using `n_link`
* Correct DoFs with `link_nodes` in `ForcedResponseResults` and `TimeResponseResults`
* Run Black

Fix DoF error when using "n_link"

---

CONTRIBUTING.rst

Some small improvements to the CONTRIBUTING file.

Improve contributing docs

---

ross/element.py
ross/results.py
ross/rotor_assembly.py

- Add list of plotting methods to methods that make use of Results classes.
- Add more examples to demonstrate how to use plot methods.
- Update some functions explainations

Improving documentation

---

appveyor.yml

Reverts ross-rotordynamics/ross#740
Remove codecov command from AppVeyor

Revert "Add codecov to appveyor"

---

.github/workflows/deploy-docs.yml
.github/workflows/test.yml
ross/__init__.py
ross/rotor_assembly.py
setup.py

Functionalities to add to workflow:
Adding some routines to the workflow to run after the tests.

Add Black, Isort and Codecov to workflow

---

.github/workflows/deploy-docs.yml

Try to deploy from a branch within ross repository.

Try to deploy from a branch within ross repository

---

ross/bearing_seal_element.py
ross/rotor_assembly.py
ross/stochastic/st_rotor_assembly.py
ross/utils.py

Displaying more information and increasing coverage.

Examples enhancement

---

docs/Makefile
docs/api.rst

Add results to api reference

---

docs/citing.rst
docs/conf.py
docs/index.rst

This changes the following:
- Adds a citing specific page with the bibtex entry;
- Creates a 'Contents' box to have main links in the top of the page;
- Fix binder link (0.4);

Update main page

---

.github/workflows/publish-to-pypi.yml
ross/__init__.py

Releasing v1.0.0rc1

---

.github/workflows/publish-to-pypi.yml
ross/__init__.py

Trying to fix publish action

---

ross/new_units.txt
ross/results.py

- Change pkpk from prefixe to constant
- Add docs on the use of 'major' and 'minor'

change pkpk constant

---

docs/conf.py

- Add html_js_files for plotly

fix plot docs

---

docs/conf.py

This one follows this suggestion:
https://github.com/readthedocs/sphinx_rtd_theme/issues/788#issuecomment-585785027

Trying to add js again

---

docs/_templates/autosummary/base.rst
docs/_templates/autosummary/class.rst
docs/_templates/layout.html
ross/results.py

- Fix disk scale factor and add test
- Fix disk doctest
- Add templates to document methods

add template

---

ross/bearing_seal_element.py

Correct an error in the damping coefficient of the Magentic Bearings Element

---

ross/bearing_seal_element.py
ross/tests/test_bearing_seal_element.py

This changes the save and load methods for bearings in order to have
additional info in the save file, such as attributes used in bearing
initialization.
Closes #820.

Improve bearing save method

---

ross/rotor_assembly.py
ross/tests/test_rotor_assembly.py

Add check units to run modal

---

.readthedocs.yaml
docs/release_notes/release_notes.rst
docs/release_notes/version-1.0.0.rst
docs/release_notes/version-1.1.0.rst
docs/requirements.txt
ross/__init__.py
setup.py

- Remove commands not used in setup.py
- Add specific requirements to build docs
- Add release notes for v1.1.0
- Bump v1.1.0 release

New release 1.1.0

---

ross/rotor_assembly.py

Now we check all elements that are connected to the specific node with:
self.df_shaft[
(self.df_shaft.n_l == n) | (self.df_shaft.n_r == n)
].
And for the inner diameter we consider the min diameter of the elements
and for the outer diameter we consider the max.
Closes #855.

Change how we get nodes inner and outer diameter

---

ross/point_mass.py
ross/rotor_assembly.py

Since we have changed bearing sizes, the example for bearings + support does not work.
This solves this problem by:
- Fix y_pos and y_pos_sup
- Change radius for point mass

Fix support plot

---

docs/discussions/discussions.md
docs/discussions/example_16.ipynb
ross/results.py
ross/rotor_assembly.py

- Fix tutorial support and bearings plot
- Add check units to campbell
- Add plot orbit method
- Add new examples
- Add examples to documentation

Add more examples to discussions

---

docs/discussions/discussions.md
docs/discussions/example_16.ipynb
ross/bearing_seal_element.py
ross/results.py
ross/rotor_assembly.py
ross/tests/test_bearing_seal_element.py
ross/tests/test_units.py
ross/units.py

- Fix tutorial support and bearings plot
- Add check units to campbell
- Add plot orbit method
- Add new examples
- Add examples to documentation
- Add dynamic-absolute viscosity to units
- Add cylindrical bearing
- Add cylindrical bearing

add cylindrical hydro bearing

---

docs/discussions/discussions.md
ross/bearing_seal_element.py
ross/rotor_assembly.py

- Add more steps to BearingFluiFlow example
- Deal with ranges that contain 0 speed
- Add example 21 with CylindricalBearing

Add example 21

---

ross/bearing_seal_element.py

Fix converting units when plotting multiple coefficients

---

ross/fluid_flow/cylindrical.py
ross/tests/test_cylindrical.py

Adding to cylindrical Lund method to calculate dynamics coefficients.

Lund Method

---

.pre-commit-config.yaml
ross/rotor_assembly.py

- Raise error when a bearing is not connected
Closes #889.

add n link error

---

ross/fluid_flow/cylindrical.py

Fix lund method in cylindrical bearing

Fix lund method

---

ross/results.py
ross/rotor_assembly.py
ross/tests/test_stochastic_elements.py
ross/utils.py

Fixing Testing Issues

---

docs/references/api.rst
ross/bearing_seal_element.py
ross/defects/crack.py
ross/defects/integrate_solver.py
ross/defects/rubbing.py
ross/fluid_flow/cylindrical.py
ross/fluid_flow/fluid_flow.py
ross/results.py
ross/rotor_assembly.py
ross/shaft_element.py
ross/stochastic/st_bearing_seal_element.py
ross/stochastic/st_results.py
ross/stochastic/st_shaft_element.py
ross/tests/test_crack.py
ross/tests/test_cylindrical.py
ross/tests/test_misalignment.py
ross/tests/test_rubbing.py
ross/tests/test_shaft_element.py

Now, the `PointMass` class is listed in the documentation.
Closes #900

API Reference Fix - PointMass added

---

ross/results.py
ross/tests/test_rotor_assembly.py

Digits Changed

---

ross/results.py

Freq Response Magnitude label changed

---

ross/materials.py

Material density unit

---

ross/tests/test_bearing_seal_element.py
ross/tests/test_disk_element.py
ross/tests/test_materials.py
ross/tests/test_rotor_assembly.py
ross/tests/test_shaft_element.py

Inequality tests

---

.github/workflows/test.yml
CONTRIBUTING.md
README.md

Migrates the repository default branch from master to main

Migrate default branch from master to main

---

ross/bearing_seal_element.py
ross/units.py

Bearing Docstring

---

ross/results.py

Add plot_bode in ForcedResponseResults

---

ross/results.py

This PR resolves #962  . Created  ` def data_mode ` in `Model_Results` class for access via df.

Add data_mode()

---

ross/__init__.py
ross/fluid_flow/cylindrical.py
ross/fluid_flow/lubricants.py
ross/results.py

Lubricants in file python

---

CONTRIBUTING.md
setup.py

- Add sphinx-design to dev requirements
- Fix git instructions headers
- Fix links and text
- Add ROSS structure explanation
- Add instruction about checking out PRs

improve contributing

---

ross/rotor_assembly.py
ross/tests/test_results.py
ross/tests/test_rotor_assembly.py

Fix slowest tests

---

ross/disk_element.py

This adds the formulas used and reference for the disk properties
calculation when using the from geometry method..

Improve disk from geometry documentation

---

ross/defects/abs_defect.py
ross/results.py
ross/stochastic/st_results.py

Converting angle of the probe

---

docs/requirements.txt

This PR resolve issue #1040 and #759 .

Update version libraries for site

---

ross/results.py
ross/rotor_assembly.py

Fix click callback function of campbell plot with mode shape

---

ross/rotor_assembly.py

This pull request includes the changes proposed in the issue #1049.

UCS map tutorial updated

---

ross/results.py

Default axis unit campbell for rpm

---

requirements.txt

numpy version <2.0.0

---

docs/_static/custom.css
docs/getting_started/installation.md
docs/references.bib
docs/user_guide/user_guide.md
requirements.txt
ross/bearing_seal_element.py
ross/results.py
ross/rotor_assembly.py
ross/tests/data/rotor_example_compressor.toml

This PR resolve issues #995 , #1057 and #1058

Dev new tutorials

---

README.md
paper/paper.md

Change link binder server

---

ross/rotor_assembly.py

This method will modify elements create in rsxl to ross only elements so that the saved file can be loaded without rsxl.

Add method to save ross only model

---

ross/stochastic/st_results.py

Fix probe class usage in stochastic module

---

ross/coupling_element.py
ross/results.py

Some adjustments were made to the `_classify` method in the `Shape` class to enhance the identification of torsional modes, particularly in multi-rotor systems.
Additionally, an error was identified in the `_patch` function of the `CouplingElement` due to the integration of the `MultiRotor` class, which has also been corrected.
____
Some of the results obtained with the improvement of  `_classify` method can be seen below:

Fix Campbell for torsional modes

---

docs/release_notes/release_notes.rst
docs/release_notes/version-1.5.0.rst
docs/release_notes/version-1.6.0.rst

Add release notes for v1.5 and v1.6.

Add release notes for v1.5 and v1.6
