doc/git_configuration.rst
This adds some instructions to set upstream as the default location from
which your repository will pull. This can also be done by editing the
config file inside the .git directory. It also adds a configuration
option so that branchs from pull requests will also be easily available.
=> Add instructions to set upstream as default

ross/rotor_assembly.py
The rotor geometry was plotted when the object was instantiated. The
purpose of this was to show the user the rotor geometry so that the user
could check if everything was correct before eigenvalues, eigenvectors
etc. were calculated.
The problem with this approach is that the rotor will be automatically
plotted in situations where this is not wanted by the user, such as when
running a script where several rotors will be instantiated or when we
are running the tests locally, in this case, several windows with plots
will appear and the tests will take a long time.
With this PR the plot of the rotor after instantiation will be optional
to the user. A message is provided to let the user know that the
plot_rotor() method can be used.
Additionally, the message "calculate eigenvalues and …
=> Remove plot when creating rotor

README.md
This changes the appveyor badge that appears in the repository main page
to track only builds that are related to the master branch.
We should have the badge only for the master branch since PRs with
failing builds will not be merged anyway.
The previous badge was tracking all builds, including those from new
pull requests that were failing before merging to master.
=> Change appveyor badge to track master

ross/bearing_seal_element.py, setup.py
Two methods were added to bearing element. The first one allows instantiating a bearing object from a table. The second one converts from table to dictionary, that can be saved as a toml file.
Close #79
=> Add methods to allow inputs from table in bearing element

ross/bearing_seal_element.py
If the user tries to instantiate a bearing element from a table and the
table contains invalid entries, such as empty cells, the program will show a
warning message and replace these cells with a zero value.
Close #97
=> Add warning for invalid table entries

ross/fluid_flow/fluid_flow.py
The center of the graphic was previously the center of the
stator, but then we could not calculate the stator radius
as a function of the rotor radius.
In relation to issue #98
=> Change graphic origin to be the center of the rotor

ross/fluid_flow/fluid_flow.py
When instantiating the fluid flow class, the program will check if the parameters given create a valid structure, i.e., with a rotor that is inside the stator. If they don't, it will plot the eccentricity and exit with a error message. Close #98
=> Add check to see if rotor is inside stator

ross/rotor_assembly.py
The function interp1d was used but the interpolate function was not being
imported.
=> Added interpolate to rotor_assembly.py

ross/fluid_flow/fluid_flow.py, ross/tests/test_fluid_flow.py
The eccentricity ratio function was being calculated wrongly, using the sommerfeld number instead of the modified one, as it was supposed to use.
=> Fix eccentricity ratio function

ross/bearing_seal_element.py, ross/disk_element.py, ross/rotor_assembly.py, ross/shaft_element.py
There was an error that shaft elements were plotting with 2 times their respective radius.
I enlarged the plot window size and distributed the axis size so that the rotor is presented with the correct proportions in relation to its dimensions.
Also, adds the slenderness ratio parameter (equation: G * A * L ** 2 / E * I ) to each shaft element. It calculates the ratio using some global distance measures, rather than basing it upon individual element dimensions. The user is returned an warning message if it's lower than a certain value, which could affect the convergence analysis.
=> Improving plot_rotor

ross/disk_element.py, ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
This is mostly to add "run_" to some Rotor methods, like:
* campbell;
* forced_response;
* mode_shape;
* static
Also, change the value to evaluate the slenderness ratio (SR) to 1.6. Since our convergence analysis have shown good results even for SR < 30, I decided changing it for 1.6, which is equivalent to a length / diameter ratio of 0.5.
=> Change methods' names

setup.py
In order to upload to PyPi, the name in setup.py should be unique. As 'ross' was already taken, we changed to 'ross-rotordynamics'.
=> Change name variable in setup

ross/rotor_assembly.py
This removes bokeh show() from the convergence and static analysis.
Automatically showing the plots is not expected when running tests or
scripts. With this modification, the figure is returned and the user can
plot that if wanted.
As an example:
```python
static_analysis = rotor.run_static()
show(static_analysis)
```
=> Remove show() from convergence and static

.travis.yml, appveyor.yml, docs/conf.py, requirements.txt, setup.py
This removes the requirements file avoiding the need to have the
dependencies listed in two different files.
With the modifications the user can install with:
`$ pip install .`
And a developer can use:
`$ pip install -e .[dev]`
which is also used on the appveyor/travis files.
=> This removes the requirements.txt file

ross/bearing_seal_element.py, ross/tests/test_bearing_seal_element.py
Fixes the equality for bearing element, allowing the comparison with
objects from different types, e.g. bearing == 1 will return False,
before an AttributeError was raised since int doesn't have .__dict__.
This also removes pytest as a dependence for the user.
=> Fix equality for bearing element

ross/results.py
Improvements according to Issue #163 
- Enlarges the scatters being plotted;
- Standarizes colors and scale between bokeh and matplotlib;
- Inserts transparency in the box caption;
- New feature: bokeh plot sizing auto adjusts to the screen.
=> Standarize Campbell diagram

docs/installation.rst
Add instruction to use Anaconda prompt on Windows.
Closes #165 .
=> Add instruction to anaconda prompt

ross/results.py, ross/rotor_assembly.py
The import has been added to the results module because the mode shape
plot needs this to work. Although it looks like the import is not being
used (this is highlighted by linters), matplotlib, for some strange
reason, actually needs this to use the projection='3d'.
A doctest has been added to the mode shape plot for the tests to fail
if this import is removed.
=> Add import to Axes3d

docs/local_coordinates.svg, ross/bearing_seal_element.py, ross/disk_element.py, ross/element.py, ross/fluid_flow/fluid_flow.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_disk_element.py, ross/tests/test_shaft_element.py
Adds `.dof_local_index()` and `.dof_global_index()` methods to the elements.
These methods will return namedtuples with the index for each coordinate based on the following convention:
As an example:
```python
>>> import ross as rs
>>> from ross.materials import steel
>>> le = 0.25
>>> i_d = 0
>>> o_d = 0.05
>>> sh_el = rs.ShaftElement(le, i_d, o_d, steel, n=2)
>>> sh_el.dof_local_coordinates()
LocalIndex(x0=0, y0=1, alpha0=2, beta0=3, x1=4, y1=5, alpha1=6, beta1=7)
>>> sh_el.dof_global_coordinates()
GlobalIndex(x0=8, y0=9, alpha0=10, beta0=11, x1=12, y1=13, alpha1=14, beta1=15)
```
With this we can change the following code:
```python
for elm in self.shaft_elements:
n1, n2 = self._dofs(elm)
M0[n1:n2, n1:n2] += elm.M()
for elm in self.disk_elements:
n1, n2 = self._dofs(elm)
M0[n1:n2, …
```
=> Index method

docs/conf.py, docs/sphinxext/sphinx_copybutton/__init__.py, docs/sphinxext/sphinx_copybutton/_static/sphinx_copybutton.css, docs/sphinxext/sphinx_copybutton/_static/sphinx_copybutton.js
Add a copy button to code blocks:
It was implemented using the sphinx-copybutton extension.
I have decided to copy the code with the license so that we can change which blocks have the copy button and also the button size.
=> Add copy button to code blocks

ross/tests/test_rotor_assembly.py
The purpose of this test is to check if the index of the sorted
eigenvalues are the same on windows and linux.
Values were different when trying doctest.
Closes #145
=> Add test to rotor_example eigenvalues sort

pytest.ini, setup.py
Code coverage is broken due to commit 97956c9 which removed the codecov
from the travisci installation packages.
Closes #235
=> Fix code coverage

ross/utils.py
Rows full of NaNs will be dropped. A check based on the header key word
will be made to find rows in which NaNs are present. Those will be
dropped as well, remaining only rows with NaNs in columns that are not
relevant.
Close #240
=> Change drops of NaNs from table

ross/results.py
Pull Request to fix Issue #243 
- Slightly increases the size of the figures
- Arrows have a fixed length now (as shown in this figure below);
- Arrows now have different colors to distinguish forces (from shaft, disks or bearings/seals);
- Labels were rotated 90º;
- Text font size reduced to "9pt";
- Y axis is hidden. The force values are only displayed only next to the arrows, without size ratio.
=> Make Free-Body Diagram more readable

ross/bearing_seal_element.py, ross/disk_element.py, ross/rotor_assembly.py
- Bearing representation changes from a simple square to a spring-damper set.
- Fix bug glyphs were plotted on the minimum outer diameters of a shaft node.
- Removes length attribute from `patch()` and `bokeh_patch()` of BearingElement and DiskElement classes.
Bokeh plot
Matplotlib plot
=> Replace bearing plot style / remove element length dependency from glyphs

.travis.yml, pytest.ini
This changes the pytest.ini file and the .travis.yml file so that
pytest-cov will run only on travis. If the user wants to run locally,
they will have to call $pytest --cov=ross.
=> Change codecov to run only on ci

ross/bearing_seal_element.py
=> Fix typo in __repr__

ross/materials.py, ross/tests/test_materials.py
Material repr and eq methods have been updated so that the following
will work: mat == eval(repr(mat)).
This is a standard way to test repr methods, since they should be
unambiguous to help debug.
Closes #230
=> Add test materials

ross/bearing_seal_element.py, ross/tests/test_bearing_seal_element.py
This fixes the interpolation code for the cases where the array
dimension is < 4. UnivariateSpline won't work for 3 or 2 points, so
these cases are now handled with interp1d.
Closes #253
=> Fix bearing interpolation error

ross/bearing_seal_element.py, ross/disk_element.py, ross/rotor_assembly.py
Disk, bearing and seal elements now get an attribute called "Tag".
This allows the user to name the elements to help refer to the actual equipment (impellers, blades, labyrinth seal...)
If the user do not input a tag, it's named after:
- Disk 1, 2, 3... 
- Bearing 1, 2, 3...
- Seal 1, 2, 3...
As bearings and seals are input in the same list of objects, this situation below may happens:
```
def rotor_example():
i_d = 0
o_d = 0.05
n = 6
L = [0.25 for _ in range(n)]
shaft_elem = [
ShaftElement(
l, i_d, o_d, steel, shear_effects=True, rotary_inertia=True, gyroscopic=True
)
for l in L
]
disk0 = DiskElement.from_geometry(
n=1, material=steel, width=0.07, i_d=0.05, o_d=0.28
)
disk1 = DiskElement.from_geometry(
n=3, material=steel, width=0.07, i_d=0.05, o_d=0.28, tag="disk_test"
)
disk2 = …
```
=> Add new "Tag" attribute to elements

ross/rotor_assembly.py, ross/shaft_element.py
Now the convergence analysis uses the class ShaftTaperedElement to generate shaft elements since it's more generic.
This should solve issue #280.
=> Adapt convergence analysis to ShaftTaperedElement

ross/results.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_rotor_assembly.py
This is related to #100. On that issue the problem was related to
the length of BearingElement being considered on the list. The problem
with that fix is that the list comprehension was not considering the
case where we have a shaft with different layers. In this case the
length for elements on different layers would be inserted on the list,
causing the plot to be wrong.
=> Fix modes shape plot

ross/bearing_seal_element.py, ross/tests/test_bearing_seal_element.py
This PR adds two new classes:
- BallBearingElement
- RollerBearingElement
These classes create a bearing element for ball and roller bearings models. They are instantiated based os some geometric and constructive parameters like: number of rotating elements, size (diameter for ballbearing; length for rollerbearing) of the rotating elements, contact angle, and static loading force. 
The direct stiffness coefficientes are calculated using these parameters.
I also left an opened option to instantiate the direct damping coefficients. But if it's set as None, they are calculated based on the stiffness coefficient as the literature suggests.
However the cross-coupling coefficients are set to zero, and the coefficients are not dependent on speed.
```
def __init__(
self,
n,
n_balls,
d_balls,
fs, …
```
=> Add BallBearing and RollerBearing Element

ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_shaft_element.py
- Add a condition if the user do not attribute any value to inner and outer diameters on the right side, the values are automatically set to be equal the left side.
- Also, move the "material" input to the first position, so the geometric parameters can be grouped together.
- Adapt the examples in docstring.
- Moves the inputs from ShaftTaperedElement to match the new position set.
```
class ShaftTaperedElement(Element):
def __init__(
self,
material,
L,
i_d_l,
o_d_l,
i_d_r=None,
o_d_r=None,
n=None,
axial_force=0,
torque=0,
shear_effects=True,
rotary_inertia=True,
gyroscopic=True,
shear_method_calc="cowper",
tag=None,
):
if i_d_r is None:
i_d_r = i_d_l
if o_d_r is None:
o_d_r = o_d_l
```
=> Add condition to ShaftTaperedElement instantiation

ross/results.py
Remove a conversion factor (meters to milimeters) from the plot_deformation() ColumnDataSource.
So the x and y axis units get to be the same.
Related to Issue #312
=> Remove unit conversion factor

ross/point_mass.py
This commit adds the following methods to PointMass class:
* __repr__ - representative method;
* __eq__ - comparasion method;
* point_mass_example() - to run some doctests.
=> Add __repr__, __eq__, and example() to point mass element

setup.py
We do not need this requirement since we have changed appveyor script
see commit 745b79c7c9a4992e785b114e3f1554d4886df403:
```
- "%PYTHON%\\python.exe setup.py test"
+ "%PYTHON%\\python.exe pytest ross"
```
=> Remove setup_requires for pytest-runner

ross/bearing_seal_element.py
We use Interp1d for cases where we can not use UnivariateSpline.
UnivariateSpline has the extrapolation as the default, but interp1d does not
extrapolate and will raise an error unless extrapolation is explicit
defined on the fill_value argument.
There are also some format changes because of running black.
=> Add extrapolate to interp1d

ross/results.py
This is related to Issues #326 and #328.
- Introduce a condition to add the hover tool only if an harmonic crosses a critical speed curve.
- Remove some unused imports.
- In _plot_bokeh:
- Change colormap from viridis to Red-Blue
- Add diferent colors to harmonics lines
- Make glyphs on legend with same color
- In _plot_matplotlib:
- Add diferent colors to harmonics lines
- For both methods:
Restructure code to increase efficiency (reduce plotting time): I could the plot time in an half by rearranging some routines.
```
import ross as rs
rotor = rs.rotor_example()
camp = rotor.run_campbell(np.linspace(0, 1000, 10)).plot([0.25, 0.5, 1, 2])
show(camp)
```
I've measured the time just to run the .plot(). It was taking 2.5s for the rotor_example(). Rearranging the code, it has been reduced to …
=> General Modifications in CampbellResults

ross/results.py, ross/rotor_assembly.py, ross/shaft_element.py
Related to Issue #327.
It's a first idea from what the summary will become.
The class get the values stored in dataframes and turns them into a bokeh widget in table format.
We still can build other tables to make it more complete and useful to manipulate data.
=> Add summary table to plot rotor information

ross/api_report.py
- This analysis consider a anticipated cross coupling QA based on conditions at the normal operating point and the cross-coupling required to produce a zero log decrement, Q0.
- Add attribute "rotor_type" 
- This attribute is necessary to distinguish overhung and between bearings rotors.
- The unbalance forces and and the respective nodes where they are introduced depends on this information.
- Improve unbalance force method.
- With this improvement, the unbalance forces are calculated according to the rotor_type and 
consideres the disks and shaft wheight (if overhung).
- Change mode_shape to find nodes according to rotor_type
- The method .mode_shapes() was capturing the maximum points from the rotor's mode shapes without checking if it was overhung or between bearings.
- For rotors …
=> Add Stability Level 1 analysis

ross/results.py, ross/rotor_assembly.py
- add a summary table for bearing elements: for now it displays only where it's placed and the reaction forces.
- fix bug: when setting and disk or bearing element in the last node, the code would fail
- other minor changes
=> Add Bearing Summary Table

ross/rotor_assembly.py
- Fix bug when plotting bearing elements in a given node with more than 1 shaft element on it. The bearing would not get correct starting point.
- Fix bug when using scale_factor with point mass. The auxiliar bearing would disattach from the first bearing.
=> Fix bug when plotting bearings

ross/tests/test_shaft_element.py, ross/utils.py
When loading a shaft element from an excel file, at some point the index was being reduced in 1.
I created this solution so that indexes would start on 0, as in every example they would start on 1. I was afraid indexes starting on 1 would create bugs in other parts of the code, but I didn't implement the same solution to disk elements. I also did not consider that the user could start their index on 0, which would cause it to start on -1.
This PR removes this index modification.
Close #368
=> Fix shaft element index

ross/disk_element.py, ross/tests/test_fluid_flow.py, ross/tests/test_shaft_element.py, ross/utils.py
As per #368, we had an inconsistency between imported shaft and disks.
PR #372 changed the shaft index, removing the lines that would change the index from 1 to 0 based. The problem is that the imported shaft and disks would be 1 indexed, and python (and ross) are 0 based, so I believe it is better to apply the 0 index to both, shaft and disks imported.
Closes #367
=> Change imported index

ross/api_report.py, ross/results.py, ross/tests/test_api_report.py
The labels, ticks and titles font size from bokeh figure were small when putting it presentations. So I've increased the font size of all graphs.
- Add new tab to the `.summary()` with stability level 2 data;
- Change stability level 2 labels for better user understanding when using `.summary()`. The labels include explicitly all the components considered in a certain analysis (Shaft + Bearing + Disk + Seal...);
- Increases labels, titiles and tick font sizes (results.py and api_report.py);
- Add mcs speed to evaluate mode shapes (api_report.py);
- Fix `.unbalance_response()` plot size to match results.py file;
- In `.stability_level_1()` remove condition from returning and add it as attribute;
- `.run_modal().plot_mode()` add legend informing the whirl direction.
=> Visual improvements to graphs

ross/results.py, ross/rotor_assembly.py
- Add `.run_orbit_response()` method to rotor_assembly.py.
- `.run_orbit_response()` calculates the orbit for a rotor's given node, speed and forces.
- Add class `OrbitResponseResults` to results.py.
- Class used to store results and provide plots for orbit response.
Example using this new method:
```
>>> rotor = rotor_example()
>>> speed = 500.0                                           # pick a rotor speed
>>> size = 10000                                            # time array's size
>>> node = 3                                                # node of interest
>>> t = np.linspace(0, 10, size)                            # create time array
>>> F = np.zeros((size, rotor.ndof))                        # create force vectors
>>> F[:, 4 * node] = 10 * np.cos(2 * t)                     # …
```
=> Add method to plot orbit

ross/api_report.py, ross/bearing_seal_element.py, ross/disk_element.py, ross/fluid_flow/fluid_flow_graphics.py, ross/point_mass.py, ross/results.py, ross/rotor_assembly.py, ross/shaft_element.py
Bokeh library has updated to 1.4.0 version lately, and as you have noticed, several warnings about "legend" attribute getting deprecated has appeared. 
This PR update legend to legend_label according to the new sintaxe shown [here](https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html).
=> Update the syntax of the legend attribute from bokeh figures

docs/conf.py
As explained on the sphinx docs
(https://www.sphinx-doc.org/en/1.8/usage/extensions/math.html), math
can be rendering using different methods. We were using the imgmath
method, which requires latex installed on the machine. Since our
documentation is built on Travis CI, we would need to install latex
there, but it seems that this is not a simple task as explained here:
https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci
The other option is to use mathjax, and the math gets rendered online
by the javascript package. We are adopting this method now.
With this modification the page is rendered like this:
Closes #384.
=> Change math rendering mode from imgmath to mathjax

docs/conf.py, docs/index.rst, docs/installation.rst
The team decided that we should use capital letters on texts for the package
title, since it is an acronym. In the code the package name remains
ross to comply with pep 8 requirements for packages and modules (all
lowercase letters).
=> Change ross to uppercase letters - ROSS

ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
As requested in Issue #401, the user will be able to define a material when using `.from_section()` classmethod.
In addition, more modifications have been done regarding the new ShaftElement API.
Now, the user has the option to instantiate tapered sections.
=> Allow user choose material in "Rotor.from_section()"

ross/bearing_seal_element.py, ross/disk_element.py, ross/element.py, ross/point_mass.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_disk_element.py, ross/tests/test_point_mass.py, ross/tests/test_rotor_assembly.py, ross/tests/test_shaft_element.py
Related to Issue #382.
We were having problems to define de global indexes for the elements using this method intenally to a element class.
It makes more sense to use .dof_global_index() when build the rotor model.
The routine to calculate the elements' global indexes have been moved to rotor_assembly (`.__init__()` method).
Now, each element has an attribute that keeps those index, instead of calling a function to this job.
=> Fix links not working for more than one support

ross/fluid_flow/fluid_flow.py, ross/tests/test_fluid_flow.py
I think the modifications I made reduced the time spent on testing as requested in issue #442 , but the `test_find_equilibrium_position` function is still slow because it is an iterative method.
=> Fix grid to decrease testing time

MANIFEST.in, requirements.txt, ross/__init__.py, setup.py
This PR adds the requirements.txt (closes #461) file and also solves the issue regarding the new_units.txt file missing after installation.
=> Add requirements.txt file

.flake8
File configuring options for code formatting.
Related to Issue #463. I copied the file from Black repository and I did some adjustments to fit our repository. As we're using Black with default options (max line length equals to 88) I set the .flake8 file to max line length to 88 either (we can change it later).
=> Configuring flake8 

ross/fluid_flow/fluid_flow_graphics.py, ross/results.py, ross/rotor_assembly.py
Related to Issue #472 
- In `results.py`
- Replace invalid escape sequence to create greek letters by actual greek letters
- Replace bokeh.widgetbox by bokeh.Column due deprecation warning
- Update docstrings
- In `api_report.py`
- I'll commit in this file when PR #477 is merged.
- In `rotor_assembly.py`
- `Iterable` now is imported from `collections.abc` instead of `collections` 
- In `fluid_flow_graphics.py`
- Replace `legend` by `legend_label` when plotting with bokeh
=> Removing deprecations and warnings

README.md, docs/download.rst, docs/examples.rst, docs/examples/example_1.ipynb, docs/examples/example_2.ipynb, docs/examples/example_3.ipynb, docs/examples/example_4.ipynb, docs/examples/example_5.ipynb, docs/examples/example_6.ipynb, docs/examples/example_7.ipynb, docs/examples/example_8.ipynb, docs/examples/example_9.ipynb, docs/index.rst
This adds a binder link to the docs web page.
It also renames the example notebooks to numerical title.
Related to #473 .
=> Add binder link

ross/units.py
Related to Issue #511 
Add a condition to verify if the argument value is None. It allows the user to pass "None" args without getting an error with the code trying to assign a unit to a None value.
=> Fix issue with check_units

ross/stochastic/st_bearing_seal_element.py, ross/stochastic/st_disk_element.py, ross/stochastic/st_materials.py, ross/stochastic/st_point_mass.py, ross/stochastic/st_results_elements.py, ross/stochastic/st_shaft_element.py, ross/tests/test_stochastic_elements.py
- Add `.plot_random_var()`: a method to plot histograms with the Frequency or the PDF for random variables.
- Add tests for `.plot_random_var()`
Example:
```
kxx = np.random.uniform(1e6, 2e6, 1000)
cxx = 1e3
elm = ST_BearingElement(n=1, kxx=kxx, cxx=cxx, is_random=["kxx"])
show(elm.plot_random_var(["kxx"]))
show(elm.plot_random_var(["kxx"], density=False))
```
The pdf estimation use the "kernel density estimation" tool from Scipy.
=> Plotting statistics for random variables

ross/stochastic/st_shaft_element.py
- The parameters `axial_force` and `torque` were missing from the `ST_ShaftElement.__init__()`.
=> Fix missing parameters in ST_ShaftElement

ross/stochastic/st_results.py, ross/stochastic/st_rotor_assembly.py, ross/tests/test_stochastic_rotor_assembly.py
This PR adds methods to plot stochastic orbits using `.run_time_response()` method from `ST_Rotor` class.
EDIT:
Just to clarify how it works, The user runs a stochastic time response analysis and it's given 3 options for plotting the results:
1. plotting 1D: amplitude vs time for a given degree of freedom.
2. plotting 2D: orbit of a node from the rotor.
3. plotting 3D: orbits of all nodes from the rotor. 
Example:
```
>>> import ross.stochastic as srs
>>> rotors = srs.st_rotor_example()
>>> size = 1000
>>> ndof = rotors.ndof
>>> node = 3 # node where the force is applied
>>> dof = 9
>>> speed = 250.0
>>> t = np.linspace(0, 10, size)
>>> F = np.zeros((size, ndof))
>>> F[:, 4 * node] = 10 * np.cos(2 * t)
>>> F[:, 4 * node + 1] = 10 * np.sin(2 * t)
>>> results = …
```
=> Plotting stochastic rotor orbit

ross/disk_element.py, ross/point_mass.py, ross/shaft_element.py
Bokeh already inserts a colon between key and value in the hover, so
we need to remove this, otherwise we get duplicated colons.
=> Remove duplicated colon from hover tool

ross/rotor_assembly.py
Related to Issue #571.
Seals can be displayed in different colors than bearings
=> Fix missing y_pos and y_pos_sup in df_seals

ross/rotor_assembly.py
If the user is not worried about the slenderness ratio this warning can
pollute the output screen. This avoids raising the warning when we are
not checking the slenderness ratio.
=> Raise warning only if check_sld is True

ross/api_report.py, ross/results.py, ross/rotor_assembly.py
Plotly has a way to check where the user is running the code and it
will set the renderer accordingly.
This also removes the dimensions for the figure of the rotor.
We used to define the figure width and height, but plotly has a way to 
identify the dimensions of the place where the user is plotting 
(notebook, browser etc.) and it will plot the figure with a proper 
dimension.
Closes #575.
=> Remove line setting renderer to browser

ross/api_report.py, ross/bearing_seal_element.py, ross/element.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/stochastic/st_rotor_assembly.py
This adds an option to run plot_ucs with synchronous option, where the
rotor speed will be equal to the frequency of the first forward mode.
This was implemented with the following steps:
1. Run modal analysis with speed=0;
2. Get frequency of first forward mode;
3. Run modal analysis with speed=<frequency from step 2>.
The time to run the speed=0 method:
10.3 s ± 1.03 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
The time to run synchronous=True method:
42.7 s ± 3.24 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
Regarding this method:
"Also, the rotor transverse inertia, It, is replaced with the
transverse minus the polar inertia (It-Ip). This last modification, in
effect, constrains the rotor rotational speed to equal the eigenvalue
frequency."
We are still evaluating how …
=> Add synchronous option to plot_ucs

ross/results.py, ross/rotor_assembly.py
Related to Issue #569.
After running the method `.run_unbalance_response()` the user is able to call a `.plot()` method to display the amplitude and phase vs frequency response.
This PR adds an alternative method to plot a 3D orbit (rotor deflected shape) response for a given unbalance: `.plot_deflected_shape()`.
```
>>> rotor = rotor_example()
>>> speed_range = np.linspace(0, 1000, 101)
>>> response = rotor.run_unbalance_response(node=3,
...                                         magnitude=10.0,
...                                         phase=0.0,
...                                         frequency_range=speed_range)
>>> fig = response.plot(dof=13)
>>> speed = 900
>>> fig = response.plot_deflected_shape(speed)
```
The image below is the current output:
=> Add methods to plot the deflected shape

setup.py
Fix Issue #586.
Travis was currently getting the latest pytest pytest-cov versions. Apparently, pytest-cov bumped a new version (up to 2.10, some hours ago) that requires pytest >=4.6.
=> Pinned pytest version to 4.6 or superior

ross/api_report.py, ross/rotor_assembly.py, ross/stochastic/st_rotor_assembly.py
The eigenvalue / eigenvector solver is chosen when running the run_modal() method, and not anymore an parameter from the rotor model
=> Move "sparse" argument to run_modal() 

requirements.txt, ross/bearing_seal_element.py, ross/disk_element.py, ross/element.py, ross/materials.py, ross/point_mass.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_disk_element.py, ross/tests/test_point_mass.py, ross/tests/test_rotor_assembly.py, ross/tests/test_shaft_element.py
This PR makes some modifications to the save functions implemented in each element class:
Each element has a .save method that writes to a .toml file, if the
file already exists the method appends to the end of the file. So the
process of saving the rotor is basically an iteration over all the
rotor elements and a call to the element.save() method.
The load method goes through all items in the .toml file and calls the
elements .read_toml_data, which parses the dictionary stored in the
.toml and returns the Element.
The elements are then separated in lists and given to the cls()
constructor. ;
This also moves all saved files to /tmp/, this way running the tests will not create several files in the ross directory (closes #590).
The ShaftElement.save method also writes the properties of the …
=> Change save functions

ross/element.py, ross/rotor_assembly.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_disk_element.py, ross/tests/test_point_mass.py, ross/tests/test_rotor_assembly.py, ross/tests/test_shaft_element.py
The approach used before ('/tmp/file') would work only on unix systems
since this path does not exist on windows.
Now the tempdir is obtained using the tempfile module.
Closes #590.
=> Change tempfile to be crossplatform

ross/rotor_assembly.py
The output array from `_clustering_points()` now evaluates the results at frequency equals 0.
It will allow a better graphical visualization for the response.
=> Add frequency 0 to automatic frequency range

ross/config.py
- Class "Config" generates an object with several preset parameters to run the rotordynamics analyses. It's a must to check all the options for a correct functioning. The attributes are automatically generated and it's not possible to remove then or add new ones.
- Class "_Dict" is a subclass used to organize nested dictionaries and set each key / value as attribute for the config object.
@raphaeltimbo and @GabrielBachmann I'd like to ask for some ideas for this file. I'm trying to follow a dictionary rule, just like Plotly does, but I couldn't find a pythonic way of how to update the config options. For now the user should change one by one, and it would be exhaustive. 
I'd like to introduce a way for the user input several options at the same time, like we do with Plotly. I've been …
=> Add file to configurate rotordynamic report

ross/results.py
The color scale to represent the log_dec values ranges between 0 and 1, independently of the log_dec values calculated.
It can be manually modified by insert 2 simple kwargs: coloraxis_cmin and coloraxis_cmax. It will change
respectively the minimum and maximum values for the color scale.
Also adds exponentformat = "none" to X and Y axis for better visualization of values
Example with default options: 
```python
>>> speed_range = np.linspace(0, 3000, 51)
>>> campbell = rotor.run_campbell(speed_range)
>>> campbell.plot(harmonics=[0.5, 1])
```
Example changing the max value for the scale: 
```python
>>> speed_range = np.linspace(0, 3000, 51)
>>> campbell = rotor.run_campbell(speed_range)
>>> campbell.plot(harmonics=[0.5, 1], coloraxis_cmax=2.0)
```
=> Set default values to log_dec color scale

ross/results.py
It removes the need of creating sub arrays from interpolation to smooth some results in StaticResults.
=> Replace interp1d by line_shape from Plotly

ross/bearing_seal_element.py, ross/disk_element.py, ross/new_units.txt, ross/point_mass.py, ross/results.py, ross/rotor_assembly.py, ross/shaft_element.py, ross/tests/test_rotor_assembly.py, ross/tests/test_units.py, ross/units.py
This PR adds arguments to the plot functions so that the user can control the plot units.
As an example, for the unbalance response, now it is possible to call the plot function like this:
```python
unb = rotor.run_unbalance_response(
node=23, unbalance_magnitude=0.60458, unbalance_phase=0, frequency=freq_range,
)
unb.plot(3, frequency_units='RPM')
```
This will automatically convert the frequency units from the default 'rad/s' to 'RPM'.
There are cases where we could have one argument controlling all quantities in the plot, like:
```python
def plot_deflected_shape_3d(
self,
speed,
samples=101,
length_units="m",
fig=None,
**kwargs,
):
```
The problem with this is that, if the user wanted to see the displacement in each node in `microns` the rotor length would also be changed to `microns`, …
=> Add units to plot functions

ross/stochastic/st_bearing_seal_element.py, ross/stochastic/st_disk_element.py, ross/stochastic/st_materials.py, ross/stochastic/st_point_mass.py, ross/stochastic/st_results_elements.py, ross/stochastic/st_shaft_element.py, ross/tests/test_stochastic_elements.py
- Remove subplot titles. It was repetitive and oddly located.
- Add ross plotly theme.
- Legends are grouped to reduce graphical pollution.
- Change from_fluid_flow classmethod to calculate the bearing coefficients numerically.
- Change coefficients labels on plot_random_var. Names were too large on graphs.
- Change default option for plotting all the random variables.
- Update tests
=> General improvements in plot_random_var()

.gitignore, tools/data/c123701, tools/data/injection, tools/data/rotor_example, tools/generate_comparison_plots.py, tools/plots/index.html, tools/plots/templates/template.html
This adds a script that generates some plots for 3 different rotor
models. This helps to solve a problem we had when we changed some
property to improve the plot for a specific model, and later we would
notice that at the end the modification would be detrimental to other
models.
This, together with the plotly_theme style, closes #580.
Now we should try to make all plot modifications on the plotly_theme.py
file, and we should run the generate_comparison_plots.py script and
check the output.
After running the script, we can open the index.html file and click each
link to check the specific plot for the three models.
I have added this script to a tools directory inside the repository.
The tools directory will store some utility used for the
development of our code. This is the same …
=> Create script to generate plots

ross/disk_element.py, ross/materials.py, ross/point_mass.py, ross/shaft_element.py
`__str__` methods will highlight the unit system ROSS is using.
Since it's automatically converted to the SI, it's important to show the user, what exactly are the units.
- class `Material` - fix `__str__` unit indication
- class `ShaftElement`- format `__str__` output and add unit indication
- class `DiskElement`- add `__str__` method with unit indication
- class `PointMass`- add `__str__` method with unit indication
class `BearingElement `is not included yet. As the parameters are not floats or ints, but list, I need to work around it to convert them to string format.
=> Formatting __str__methods to include units

ross/api_report.py, ross/results.py, ross/rotor_assembly.py
- Replace `dof` by `probe `argument
- probe is a list of tuples. Each tuple refers to a probe, which must include de node and the orientation.
- The orientation units is set by `probe_units` argument.
- in `plot()` method, `data.showlegend` is turn off to avoid repetitive legend marks on graphs
=> Add probe argument to ForcedResponseResults

ross/results.py, ross/rotor_assembly.py
When plot_type="1d", users will have an option to add a list of probes (node, orientation) to return the time response for each one.
It's similar to the ForcedResponseResults.
It follows the same ideas than PR #635.
=> Add probe argument to TimeResponseResults

ross/fluid_flow/fluid_flow.py
- Remove command line running `calculate_pressure_matrix_numerical()` method without checking the argument first.
- In `calculate_pressure_matrix_numerical()`, replace loop by `numpy.clip()` method to help efficiency.
=> Remove repetitive command line

ross/results.py, ross/rotor_assembly.py
- Remove `.plot()` method.
- Users should call the method's name (`plot_1d()`, `plot_2d()`, `plot_3d()`) to display graphs, instead of using the argument `plot_type`.
=> Changing TimeResponseResults API

deploy_docs.sh, setup.py
Recent numpydoc versions (>1.0) would break the build process for our
docs. For some reason the relabel_references function from numpydoc
causes an exception and the build process stops.
I have checked the function, and it looks like the problem is in
the assert len(prefix) == HASH_LEN + 1.
Our prefix, in this case friswell2010dynamics, has a higher len than
HASH_LEN + 1, since the value for HASH_LEN is 12 in the code.
I suspect this might be related to our use of sphinxcontrib-bibtex.
For now I am going to fix this dependency version to 0.9.2 and
latter we can check this.
=> Fix dependency issue

ross/element.py, ross/fluid_flow/fluid_flow.py, ross/fluid_flow/fluid_flow_coefficients.py, ross/fluid_flow/fluid_flow_geometry.py, ross/stochastic/st_disk_element.py, ross/stochastic/st_materials.py, ross/stochastic/st_point_mass.py, ross/stochastic/st_results.py, ross/stochastic/st_rotor_assembly.py, ross/stochastic/st_shaft_element.py, ross/tests/test_fluid_flow.py, ross/tests/test_materials.py, ross/tests/test_stochastic_elements.py, ross/tests/test_stochastic_rotor_assembly.py
This PR bring some modifications to `st_results.py`. These changes aims to match what have commited to `results.py` file.
- Adds the concept of probes to `ST_TimeResponseResults`, as it's done in ROSS.
- Removes the plot() method where the user should choose one of the 3 available plotting options. Now the user calls for `plot_1d()`, `plot_2d()` or `plot_3d()` method (same syntax than `TimeResponseResults`).
- In `plot_1d()` the color schemes are removed; Plotly will auto pick the colors to avoid repeated colors when plotting several traces.
- Remove command lines updating `xaxes` and `yaxes` from Plotly. It will use ROSS plotting theme now.
=> Updating Stochastic ROSS plotting methods

ross/results.py
We were having some issues regarding to the Major Axes calculation on Modal Analysis. Depending on the rotor model, ROSS could return us mode shape plots with some kind of "discontiuity" or "leap". for example:
he 3D to 2D conversion is made by a rotation matrix, where the vector is projected on the YZ plane.
Where the first row from Rv should be 0 and the second row should be the projection. The process was made for each node with it's own rotation matrix. So, what is important to us is the ![image](https://user-images.githubusercontent.com/45969994/93242106-ab3a5480-f75c-11ea-954e-d0b5566d9e6f.png) part
To remove this kind of bug, all the projections are now rotated with the same theta angle (since they are approximately the same) - as follow in …
=> Corrections to Major Axis calculation

.travis.yml
If we have black running before_script we can have the ci failing before
running any tests. If black runs after, during a pull request review the
reviewer can at least see if all tests are passing.
=> Change travis so we run black after_script

ross/plotly_theme.py, ross/results.py
Related to Issue #675 
- Increase the figure size to a better fit of the images.
- Move the legend to the bottom
- Increase the deflected shape 3D domain in the subplot
- Changes the default values for `layout.scene.eye`. The new values zoom the view out.
=> Improving deflected shape layout

ross/results.py
These changes fix the bending moment calculation for a deflected shape configuration.
The old code was not calculating the correct values.
If we take a closer look to the bending moment diagram, we can see that in both end, the moment is numerically zero (which is supposed to be, since the rotor is simply supported). And in this symmetrical example, we have a symmetrical response (as it also supposed to be
The new algorithm is based on [1] (section 6.12)
[1] _Friswell M. I., Penny J. E. T., Garvey S. D., and Lees A. W. Dynamics of Rotating Machines. Cambridge University Press, 2010._
=> Fix _calculate_bending_moment() code

ross/bearing_seal_element.py
Users will be able to input as many frequency values as needed and `from_fluid_flow()` will run a loop calculating a set of coefficients for each given frequency.
Now, `omega` argument must be a list of frequencies.
It also changes the main function used to calculate the coefficients. `calculate_stiffness_and_damping_coefficients()` is now used to do it numerically.
=> Add loop to calculate frequency-depedent coefficients in from_fluid_flow()

ross/stochastic/st_bearing_seal_element.py
* These modifications allow the user to generate random coefficients with frequency dependency using `fluidflow`.
* The argument `omega` cannot be considered random. The user inputs a list of frequencies and the code calculate the coefficients' statistics for each frequency value.
=> Building random bearings with freq. dependent coeficients

ross/rotor_assembly.py
`PointMass` and `BearingElements` with `n_link` argument were getting non integer values. Matrices would not be built, once these values are used as reference to array indexes (which must be integers).
=> Fix GlobalIndex with non integer values

ross/stochastic/st_results.py
There was an error in the counter to build the results matrix in `ST_ForceResponseResults`. Insted of using counter "j" related to the result itself, it was using counter "i", related to the `probe` numbering.
=> Fix counter in ST_ForceResponseResults

docs/refs.bib
Author name was duplicated, causing the sphinx build to fail.
=> Fix bib file

ross/new_units.txt, ross/results.py
This adds the prefix `pkpk_` to our unit registry.
The user can now use this in plots as:
```python
import ross as rs
import numpy as np
rotor = rs.rotor_example()
speed = np.linspace(0, 1000, 101)
response = rotor.run_unbalance_response(node=3,
unbalance_magnitude=.001,
unbalance_phase=0.0,
frequency=speed)
response.plot([(0, 45)], amplitude_units='pkpk_micron')
```
Since this is a prefix, we can use it with any length units: `pkpk_m`, `pkpk_inch`, etc.
Closes #710.
=> Add prefix for peak to peak units

ross/__init__.py, ross/results.py, ross/rotor_assembly.py, ross/stochastic/__init__.py, ross/stochastic/st_results.py, ross/tests/test_results.py
This PR is a remake from PR #703. One can check the discussion history by accessing the previous link. 
Adds abstract classes "Results" and "ST_Results" that holds a generic save() and load() methods.
The other classes will inherit these methods from "Results" and "ST_Results". It avoids redundancies by repetition of functions with the same functionality.
The user will be able to save the results of a given analysis and load it later, avoiding the need to re-run the entire analysis, which could be costly.
Example of how to use it:
```python
>>> # Example running a stochastic unbalance response
>>> from tempfile import tempdir
>>> from pathlib import Path
>>> import ross.stochastic as srs
>>> # Running an example
>>> rotors = srs.st_rotor_example()
>>> freq_range = np.linspace(0, 500, 31) …
```
=> Add save() and load() methods to manage ROSS results

ross/results.py, ross/rotor_assembly.py
- New method in `ForcedResponseResults`: `_calculate_major_axis_per_node()` calculates the major and minor axes at a given node for all frequencies in `speed_range` array. Plotting methods will use this function to simplify and clear their codes.
- New option to add tags to probes in unbalance and time response. Users Will be able to name probes. If nothing is passed, it uses a default tag enumerating the probes.
An example of how these features works is shown in Issue #714.
=> Add minor and major axes to response plots

ross/results.py, ross/rotor_assembly.py, ross/stochastic/st_results.py, ross/stochastic/st_rotor_assembly.py, ross/tests/test_results.py, ross/tests/test_rotor_assembly.py
- The method `run_freq_response()` now returns, not only the displacement results, but also the velocity and acceleration. The data is then input to `FrequecyResponseResults` and `ForcedResponseResults` classes.
* Add examples about it to the docstring.
* Concatenate the parameters to fix docs presentation with Sphinx. A new parameter tab was not being displayed on the website.
- The user is able to choose the response by changing the amplitude_units argument.
Inputing '[length]/[force]', it displays the displacement;
Inputing '[speed]/[force]', it displays the velocity;
Inputing '[acceleration]/[force]', it displays the acceleration.
- Fix bug when inputing a figure and the scatters would have same colors.
- Add legend informing the input and output nodes and DoFs. It will help, mainly, …
=>  Calculate velocity and acceleration responses

ross/results.py, ross/rotor_assembly.py
These changes are applied to the methods: `plot_mode_3d` and `plot_mode_2d` from `ModalResults` class.
- Add "speed", "damping ratio" to the fixed title
- Add argument to include a tag to the title plot
- Add argument to choose between `wd`and `wn` in the plot title.
=> Customizing mode shape titles

ross/results.py, ross/rotor_assembly.py, ross/tests/test_results.py, ross/tests/test_rotor_assembly.py
Users will be able to set bounds where to catch the critical speeds.
Add option to return the whirl direction for each critical speed.
Add option to change `wn` and `wd` units.
Examples of how to use `run_critical_speeds()`
```python
>>> import ross as rs
>>> rotor = rs.rotor_example()
>>> results = rotor.run_critical_speed(num_modes=8)
>>> np.round(results.wd())
array([ 92.,  96., 271., 300.])
>>> np.round(results.wn())
array([ 92.,  96., 271., 300.])
>>> results = rotor.run_critical_speed(speed_range=(100, 1000))
>>> np.round(results.wd())
array([271., 300., 636., 867.])
>>> np.round(results.wd("rpm"))
array([2590., 2868., 6074., 8278.])
>>> results.whirl_direction # doctest: +ELLIPSIS
array([...
```
=> Add speed_range and whirl directions to run_critical_speeds()

ross/stochastic/st_bearing_seal_element.py, ross/stochastic/st_disk_element.py, ross/stochastic/st_materials.py, ross/stochastic/st_point_mass.py, ross/stochastic/st_results.py, ross/stochastic/st_rotor_assembly.py, ross/stochastic/st_shaft_element.py, ross/tests/test_stochastic_rotor_assembly.py
This PR does extensive changes to stochastic ROSS module.
- Add units support to st_rotor_assembly.py and st_results.py file.
- Add units support to elements and materials
- Update methods and classes to match ROSS and Stochastic ROSS syntax.
- Improve documentation.
=> Add units to stochastic ross module

ross/defects/misalignment.py, ross/defects/rubbing.py
This PR is related to the issue #735, where @rodrigomoliveira1 could not use the `MisalignmentFlex` and `MisalignmentRigid` classes with less than two discs.
Closes #735
=> Defects classes number of disks

appveyor.yml
While we do not change the CI from Travis to other (Issue #738) , I'm adding codecov do appveyor, so it can run coverage after testing our code
=> Add codecov to appveyor

ross/rotor_assembly.py
- This attribute was missing since it was added to `Rotor` class
- `link_nodes` is used in `ForcedResponseResults` class
- Also removes unnecessary attributes from `Rotor` and `CoAxialRotor` classes
=> Add link_nodes attribute to CoAxialRotor class

.github/workflows/publish-to-pypi.yml
This action replaces the release process that we had with travis ci. It
works in the same way and it will release a new package when we push a
tagged commit to the repository.
=> Add publish-to-pypi github action

ross/__init__.py, ross/results.py, ross/rotor_assembly.py, ross/tests/test_results.py, ross/tests/test_units.py, ross/units.py
This PR adds three additional arguments to the Campbell plot:
- damping_parameter: choose between log_dec or damping_ratio;
- frequency_range: filter out modes that are out of this frequency range;
- damping_range: filter out modes that are out of this damping range;
Closes #783.
=> Add damping parameter and filtering to campbell

ross/bearing_seal_element.py
Although we are probably not using this with seals, it keeps consistency
with BearingElement and methods such as .from_table().
=> Add n_link to SealElement

docs/conf.py
- Fix add of js file
Previous code is used when we build documentation using readthedocs,
which is not the case for ROSS.
Related to #759 .
=> fix plot docs

ross/bearing_seal_element.py, ross/rotor_assembly.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_stochastic_elements.py
Remove the auxiliary _Coefficient class in favor of a more simple data
processing within the BearingElement class.
The _Coefficient class was used to process the coefficient data,
creating the interpolation functions and also providing plots (e.g.
`bearing.kxx.plot()`). This was making the code more complicated since we
basically had to reproduce the methods of an iterable object in this
class. The discoverability of the plot function was also improved,
since it is more natural for the user to search for a plot function
within the bearing element and not as an attribute of each coefficient
(`bearing.plot('kxx')` instead of `bearing.kxx.plot()` is now used).
Another improvement regarding the plot is that the user can now pass
multiple coefficients to plot with: …
=> Remove coefficient class

ross/bearing_seal_element.py, ross/rotor_assembly.py
Numpy objects have to be converted to native types before saving to .toml.
This fixes some cases where the conversion was not being done.
=> Fix np objects conversion

ross/bearing_seal_element.py
Instead of saving all __dict__, we select values used as arguments in
the bearing initialization and the coefficients. This avoids some
errors and makes more sense, since we are not expecting to see in the
saved files information that is not available in the docstrings.
=> Change bearing save methods

ross/bearing_seal_element.py
This removes the lambda definition within the _process_coefficients
method, since lambda is not picklable this would cause an error when
trying to pickle bearing objects.
Related to #825.
=> Make bearing objects pickable

codecov.yml, ross/rotor_assembly.py, ross/tests/data/rotor.toml, ross/tests/test_rotor_assembly.py
This PR fixes the `run_static` method for rotors with seals.
I have changed the code to make sure that seals are not added to the aux_brg list used in
the static analysis.
Closes #830.
=> Fix static analysis

.pre-commit-config.yaml, ross/tests/test_bearing_seal_element.py, ross/tests/test_units.py, ross/units.py
With pint we cannot have two quantities from different registries
interacting. This can lead to problems when we have an application that
uses pint calling a package that also imports pint, since the
application registry will be different from the package registry.
To solve this problem we need to use pint.get_application_registry
within our package, so that the package (ross in this case) can use the
same registry as the application.
One problem that occured after using .get_application_registry is that
it was not possible to use the .load_definitions method, since this
would cause a unit 'redefinition' which is not allowed by pint.
To solve this, after calling .get_application_registry, we check if the
object is an instance of LazyRegistry. Basically, what this means is
that …
=> Add .get_application_registry to pint import

.github/workflows/test.yml, .pre-commit-config.yaml, ross/bearing_seal_element.py, ross/fluid_flow/fluid_flow.py, ross/fluid_flow/fluid_flow_coefficients.py, ross/rotor_assembly.py, ross/stochastic/st_bearing_seal_element.py, ross/stochastic/st_rotor_assembly.py, ross/tests/test_bearing_seal_element.py, ross/tests/test_fluid_flow.py
Black and isort do not agree on how to sort imports, this will cause
conflicting changes between these tools. With isort 5 it is possible to
have some configuration so that we can use both, but I believe just
using black is a more simple and easy approach.
=> Remove isort

.github/workflows/test.yml, docs/getting_started/installation.md, requirements.txt, ross/units.py, setup.py
Since we are now using pint 0.18 which requires python 3.7+, we can no
longer support python 3.6.
=> Remove python 3.6 support

ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
This adds an auxiliary rotor with 0 stiffness in the bearing location
to fix calculations, otherwise, a bearing a rotor with a bearing with
high stiffness would have 0 reaction force at the bearing location.
=> fix static stiff

ross/results.py, ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
This PR fixes the issues that we had with the static analysis when we added a bearing and a disk to the same node. 
It also changes the code to work with only one rotor, since this covers most of the cases and makes the code easier to maintain.
- Add failing test to represent issue #845
- Remove check for coaxial rotor
- Remove if block for multiple rotors
- Fix bearing reaction forces
=> Fix bug in static analysis with bearing and disk in the same node

ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
If a rotor model was created without a disk, the loop used to calculate
the scale factor based on the mass would fail.
Closes #856.
=> Fix plot rotor without disks

ross/results.py, ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
Fix calculation of bearing stiffness for plotting 
Since we have removed the Coefficient class we no long calculate the
bearing coefficient with bearing.kxx.interpolated. Now we use
bearing.kxx_interpolated.
Fix number of modes
It was only possible to plot 4 modes. Now we can change the num_modes
which is the number of calculated modes, and we will have that value
divided by 4 being plotted.
Value is divided by 4 because for each pair of eigenvalues calculated
we have one wn, and we show only the forward mode in the plots,
therefore we have num_modes / 2 / 2.
=> Fix ucs map

ross/results.py, ross/rotor_assembly.py
A list with critical points modal analysis results has been added to the ucs results object.
Methods to plot the 2d and 3d mode shapes have also been added to the results object.
=> Add critical mode plots to ucs

ross/results.py
.plot() method did not have a return command.
=> Fix lacking output in Level1Results

.github/workflows/test.yml, setup.py
This change aims to avoid error when installing it in python env version 3.10.6
=> Remove setup.py <3.10 version restriction

.readthedocs.yaml, docs/conf.py, docs/requirements.txt
This updates the versions of the packages used to build the docs and
remove the need to use/update the mistune library which has a CVE for
the version that we were using (0.8.3).)
Closes #940.
=> Update packages used to build docs

ross/bearing_seal_element.py, ross/rotor_assembly.py
A common requirement is to run an expensive bearing calculation and then copy this bearing and just set a different node where it will be located in the rotor:
```python
import ross as rs
from copy import copy
bearing_de = rs.SpecialBearing(n=0, ...)
bearing_nde = copy(bearing_de)
bearing_nde.n = 20
```
The above code would give an error, since in the rotor assembly we have a code which relies on bearings having n_l and n_d attributes (although this only make senses to shaft elements).
This code removes the attribute from bearing initialization and sets it at rotor initialization. This way it is possible to modify the attribute before creating the rotor.
=> Fix copying a bearing and setting node

ross/results.py, ross/rotor_assembly.py
This adds an interactive plot where the user can click a mode in the
Campbell diagram and the respective shape will be plotted in a 3d plot.
To implement this we used the 'on_click' event that is available in
plotly and is associated with each trace in the figure.
To make the plots appear in a reasonable time we had to use the
.batch_update() method, otherwise in each step of the for loop the
figure would be updated, making the rendering of the plot very slow.
For now this has only been tested in a jupyter notebook environment,
in the future we could check on how to implement this in a streamlit
app.
=> Add campbell mode shape plot

CONTRIBUTING.md, docs/getting_started/installation.md
Some website links were incorrect and out of date, for example the Anaconda installation website:
https://ross.readthedocs.io/en/stable/getting_started/installation.html
=> Fix website links incorrect

ross/bearing_seal_element.py
Hi new contributor here.  I'm trying to build some projects using your library.  I was trying to use the debugger inside Spyder to help me debug some of the code that I had written, when I noticed that I was getting errors inside BearingElement.  Interesting, this code ran perfectly outside of the debugger, but failed inside the debugger.  I tracked it down to the use of locals() in BearingElement to create a dictionary, which was later modified.  The python documentation (https://docs.python.org/3/library/functions.html#locals) explicitly says that the dictionary returned by locals() should not be modified.  In this case it appeared to lead to implementation dependent behavior. Working normally, but not inside the debugger.  I've rewritten the code such that the dictionary is read only. …
=> Fix issued related to use of locals() in bearing_seal_element.py

ross/disk_element.py, ross/rotor_assembly.py, ross/shaft_element.py
This PR resolve issue #1022 .
The Kdt matrix was also created for the disk element. However, this matrix is applied in time-dependent analyzes when there is speed variation. As the Kst matrix, it must be multiplied by the angular acceleration.
=> Fix use of Kst matrix

ross/results.py, ross/rotor_assembly.py
Issues addressed in #1043 will be resolved in separate PRs.
This PR resolves for the 6 dof model:
* the error that appear running  `run_static()` and `run_ucs()`;
* some plot issues related to the `Shape` and `ForcedResponseResults` classes.
=> Fix responses for 6 dof model

ross/rotor_assembly.py
If the rotor had bearings created in rsxl the ucs would fail when trying to call b.__class__ since the class would not be available inside ross.
=> Fix ucs for rotor with rsxl elements

docs/user_guide/fluid_flow_theory.ipynb, ross/faults/crack.py, ross/faults/misalignment.py, ross/faults/rubbing.py, ross/fluid_flow/cylindrical.py, ross/fluid_flow/fluid_flow_coefficients.py, ross/results.py, ross/rotor_assembly.py, ross/tests/test_6dof_model.py, ross/utils.py
I created some unit tests for the 6 dof model encompassing several analyzes available in ROSS. Among these tests, I included comparisons of the responses with the results from the 4 dof model.
I also used this PR to resolve several warnings (mainly related to deprecated features) that appeared in the terminal while running pytest:
```python
=========== 464 passed, 2 skipped, 798098 warnings in 96.93s (0:01:36) ===========
============= 464 passed, 2 skipped, 88 warnings in 93.82s (0:01:33) =============
```
=> Add unit tests for 6 dof model

ross/rotor_assembly.py
When I was fixing some pytest warnings related to PR #1063, I realized that there was a bug in the `run_ucs()` function. As can be seen in the figure below, critical points will only be saved if the `intersection()` function returns `x` and `y` as length-1 arrays. If this function returns arrays with more than one element, the `float()` function will not work, and the try block will be skipped.
I also had to modify the last changes made in PR #1062 to work with the 6 dof model. I came up with the following code:
```python
bearing_class = BearingElement6DoF if self.number_dof == 6 else BearingElement
...
bearings = [bearing_class(b.n, kxx=k, cxx=0) for b in bearings_elements]
```
After fixing these issues, it is possible to see the critical points in the UCS map:
=> Fix critical points in run_ucs

ross/bearing_seal_element.py, ross/rotor_assembly.py
Closes #1069
After fixing this issue, it is possible to load the .toml file:
=> Fix method of saving .toml file for the 6dof model

ross/results.py, ross/rotor_assembly.py
Resolves issue #821
This PR enhances the Shape class by adding a new function to classify mode shapes into "Lateral," "Axial," or "Torsional." With the new attribute `mode_type`, it is now possible to identify the mode shape in the Campbell diagram for the 6 dof model, leading to the creation of two new labels: “Axial” and “Torsional.”
Additionally, an issue was observed in the eigen solver results for certain 6 dof model cases. The `sigma` argument in `las.eigs()` function was previously set to 0, which resulted in poor accuracy. By adjusting `sigma` to a value slightly greater than 0, the accuracy of the results has improved. However, it is not yet clear whether the value now assumed for sigma presents good results for other cases. For more details about this parameter, refer to the …
=> Improve Campbell diagram for 6 dof model

ross/rotor_assembly.py, ross/tests/test_6dof_model.py, ross/tests/test_rotor_assembly.py
For the 6 dof model, running modal analysis has typically revealed modes with zero natural frequency, known as rigid body modes. This may result from the lack of constraints in the model and can be observed by comparing the Campbell diagrams for the 4 and 6 dof models of the same rotor system, as shown below:
However, a problem related to the convergence of Scipy's `eigen` solver was also noticed when changing the `frequencies` argument:
```python
samples = 31
speed_range = np.linspace(315, 1150, samples)
campbell = rotor.run_campbell(speed_range, frequencies=6)
fig = campbell.plot(harmonics=[0.5, 1])
```
To address this, my suggestion is to remove these zero-frequency modes after calculating the eigenvalues and increase the number of eigenvalues to be obtained from the solver:
As a …
=> Remove rigid body modes from modal analysis

MANIFEST.in, ross/assets/default.css, ross/assets/plot_with_mode_shape.css, ross/results.py
The `plot_with_mode_shape()` method of `CampbellResults` has been enhanced to improve user interaction and code maintainability. Key modifications include:
- Creation of an internal function that returns the Campbell figure and the update function of the mode shape 3D figure based on the point clicked in the Campbell figure.
- Integration of Dash framework to plot both figures, enabling interactive user experience in both web browsers and Jupyter notebooks.
- Correction of the issue related to the positioning of the legend when broken into more than one line.
=> Change plot with mode shape

ross/results.py
Now, it's possible change the x axis (rotor speed) with variable `speed_units` in plot().
```python
import ross as rs
import numpy as np
Q_ = rs.Q_
rotor = rs.rotor_example()
speed = np.linspace(0, 400, 101)
camp = rotor.run_campbell(speed)
fig = camp.plot(
harmonics=[1, 2],
damping_parameter="damping_ratio",
frequency_range=Q_((2000, 10000), "RPM"),
damping_range=(-0.1, 100),
frequency_units="Hz",
speed_units="RPM",
)
```
This PR resolve, issue #1087.
=> Change the X Axis (Rotor Speed) in Campbell Diagram

ross/bearing_seal_element.py, ross/element.py, ross/rotor_assembly.py
For some specific bearing classes (e.g. `BallBearingElement`, `RollerBearingElement`, `BearingFluidFlow`, `CylindricalBearing`), the save to .toml file method was unable to save the names of these classes due to inconsistencies between their initialization arguments and the class attributes. These issues have now been fixed and the names of the respective classes are now effectively stored in the output file to be later loaded as defined by the user.
=> Fix bearing saving method

ross/results.py, ross/rotor_assembly.py, ross/tests/test_rotor_assembly.py
Pull Request created to make corrections related to the plotting of modes in the `Results` class:
- Only information from the `Shape` class was kept.
- Unused methods were then removed.
- To avoid constant changes in the plotting of the modes in each simulation, due to the random nature of the solver initialization, the parameter `v0` of the `las.eigs` function was set with a fixed array of values.
- A limitation related to the amount of eigenvalues ​​to be found was applied when `sparse = True`.
=> Fix plotting of modes

.flake8, .github/workflows/test.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, pyproject.toml, setup.py
Based on issue #1044, this PR performs the migration from the black formatter to ruff.
=> Dev migration from black to ruff

ross/bearing_seal_element.py
In the last PR, I had accidentally removed the `kwargs`  from `BearingElements` input arguments, which ended up causing errors in some models. Therefore, I returned these arguments in this PR.
=> Return kwargs in arguments of BearingElements

ross/plotly_theme.py
Resolves #1145
____
As mentioned in issue #1145 and in [change log](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md)  of plotly, the deprecated `heatmapgl` traces were dropped from the API. 
To remove the resulting incompatibility in ROSS, the `heatmapgl` key was removed from the plotlty theme used in ROSS.
=> Drop deprecated heatmapgl traces in plotly v6.0.0

ross/multi_rotor.py, ross/results.py, ross/tests/test_rotor_assembly.py
Resolves #1168
The plot functions of the mode shapes have been adapted to improve visibility in the case of multirotors.
To differentiate the modes of each coupled rotor, markers have been added to the curves (2d and 3d).
If the model is only a single rotor and not a multirotor, the curves will not show these markers.
=> Adapt plot mode shapes for multirotor

ross/results.py, ross/rotor_assembly.py, ross/utils.py
This PR introduces a new function to convert a 6DoF rotor representation into a model with only torsional DoFs. This utility will help simplify simulations or analyses where only torsional dynamics are relevant.
- Added `convert_6dof_to_torsional()` function in _utils.py_
- Added option in `run_campbell()` to enable separated torsional analysis by setting `torsional_analysis=True` (results shown in the Campbell diagram)
- While run_modal and `run_campbell` are expected to work with the converted rotor, other methods of the `Rotor` class—such as `run_ucs` and `run_unbalance_response`—may not function correctly with the rotor object returned by `convert_6dof_to_torsional`.
- The torsional modes included in the full (6DoF) analysis may differ from those obtained in the separated torsional …
=> Create function to convert 6dof rotor to torsional

ross/results.py
This PR resolves an issue related to the `"curveNumber"` attribute in the `Campbell` figure within the `update_mode_3d` function. The attribute is named inconsistently across platforms:
- On Streamlit, it appears as "curve_number"
- On Dash, it is represented as "curveNumber"
This update introduces logic to handle both naming conventions to ensure cross-platform compatibility and prevent potential errors.
=> Fix problem related to update_mode_3d
